---
title: "Penguin Size Analysis"
date: "last version: `r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = F, echo = T, warning = F, message = F)
```

# Contact

>**Florian Orgeret**
>
>Postdoctoral Researcher
>
>Swiss Ornithological Institute
>
>Ecological Research Unit
>

# Aim

This is an example on how to make a report using rmarkdown and the palmerpenguins dataset <https://allisonhorst.github.io/palmerpenguins/articles/intro.html>.

# Packages

```{r packages}
# library(palmerpenguins) #not needed because data saved locally with 01_penguins.R
library(ggplot2)# for plotting
library(tibble)# alternative to data.frame
library(kableExtra)# for making tables
library(broom)#makes model outputs into tidy format
```

# Analysis

## Data Loading

```{r}
# activity-based directory organization ----
# (data is stored elsewhere, likely because it is too big and/or reuse for several projects)
# penguins_big <- read.csv(file.path(getwd(), "..","..", "bigdata", "penguins_big.csv"))
# the ".." allows to  move to the parent directory (here twice)

# project_based directory organization ----
# (data is inside the project directory, which allows for full reproducibility)
penguins <- read.csv(file.path(getwd(), "..", "data", "penguins.csv"))# assuming the data set is already available in 'data' from 01.penguins.R
```

## Data Summary

```{r penguins}
summary(penguins)
```

## Data Visualization

You can also embed plots, for example:

```{r, fig.align = 'center', fig.width = 10, fig.height = 8, dpi=300}
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g, color = species)) +
  geom_point() +
  geom_smooth(aes(group=1), method="lm")+
  theme_minimal() + 
  labs(title = "Penguin Size Measurement",
       x = "Flipper Length (mm)",
       y = "Body Mass (g)")
```

## Linear Regression
```{r}
model <- lm(body_mass_g ~ flipper_length_mm, data = penguins)
```

```{r}
model_params <- tibble(Parameter = names(coef(model)),
                       Estimate = coef(model),
                       Std.Error = summary(model)$coefficients[, "Std. Error"],
                       t.value = summary(model)$coefficients[, "t value"],
                       Pr = summary(model)$coefficients[, "Pr(>|t|)"])

```

```{r}
model_params %>% 
  kable("html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```


```{r}
model %>% 
  glance %>% 
  kable("html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

# Package Citation

```{r}
citation("palmerpenguins")
```

# Session Info

```{r}
sessionInfo()
```


